server:
  port: 8077
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: shopServiceRoute
          predicates:
            - Path=/shoppingcart/**
          uri: lb://shop-service
          
        - id: productServiceRoute
          predicates:
            - Path=/shoppingcart/**
          uri: lb://product-service
          
          
 
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka

management:
  endpoints:
    web:  
      exposure:
        include: "*"
  security:
    enabled: false
